language: php
php:
- 5.3
- 5.4
- 5.5
- 5.6
- 7.0
- hhvm
env:
  global:
    DOCKER_VERSION=1.12.0~rc2
matrix:
  include:
  - dist: trusty
    php: 5.6
    env: INTEGRATION_TESTS=true WORDPRESS_VERSION=45
    script: bin/integration-tests
  - dist: trusty
    php: 5.6
    env: INTEGRATION_TESTS=true WORDPRESS_VERSION=44
    script: bin/integration-tests
  - dist: trusty
    php: 5.6
    env: INTEGRATION_TESTS=true WORDPRESS_VERSION=43
    script: bin/integration-tests
  - dist: trusty
    php: 5.6
    env: INTEGRATION_TESTS=true WORDPRESS_VERSION=42
    script: bin/integration-tests
  - dist: trusty
    php: 5.6
    env: INTEGRATION_TESTS=true WORDPRESS_VERSION=41
    script: bin/integration-tests
  - dist: trusty
    php: 5.6
    env: INTEGRATION_TESTS=true WORDPRESS_VERSION=40
    script: bin/integration-tests
  - dist: trusty
    php: 5.6
    env: INTEGRATION_TESTS=true WORDPRESS_VERSION=39
    script: bin/integration-tests
  - dist: trusty
    php: 5.6
    env: INTEGRATION_TESTS=true WORDPRESS_VERSION=38
    script: bin/integration-tests
  - dist: trusty
    php: 5.6
    env: INTEGRATION_TESTS=true WORDPRESS_VERSION=37
    script: bin/integration-tests
  - dist: trusty
    php: 5.6
    env: INTEGRATION_TESTS=true WORDPRESS_VERSION=36
    script: bin/integration-tests
  - dist: trusty
    php: 5.6
    env: INTEGRATION_TESTS=true WORDPRESS_VERSION=35
    script: bin/integration-tests
  - dist: trusty
    php: 5.6
    env: INTEGRATION_TESTS=true WORDPRESS_VERSION=34
    script: bin/integration-tests
  - dist: trusty
    php: 5.6
    env: INTEGRATION_TESTS=true WORDPRESS_VERSION=33
    script: bin/integration-tests
  - dist: trusty
    php: 5.6
    env: INTEGRATION_TESTS=true WORDPRESS_VERSION=32
    script: bin/integration-tests
  - dist: trusty
    php: 5.6
    env: INTEGRATION_TESTS=true WORDPRESS_VERSION=31
    script: bin/integration-tests
  - dist: trusty
    php: 5.6
    env: INTEGRATION_TESTS=true WORDPRESS_VERSION=30
    script: bin/integration-tests
install:
- composer install
- if [[ "$INTEGRATION_TESTS" == "true" ]]; then sudo bin/install-docker; fi
script:
- bin/unit-tests
- bin/check-style --warning-severity=0 src
notifications:
  email: false
  slack:
    secure: uttJ78cpkV9czhoKXtAoop8UBWPVtF+fwKlKS47c4EW7ZfVx9jAII2yLb5yZjdLDnM7YAluujUBIqyESvwLY0h7azLsorSIEqNt9GlBi4B7DSGAdo46lFbqsdjrLwM1gOhiP7Fl4hFiQ2+jA9Fsj3W2yZ6rbF7endv7Gx5FMlFg=
