language: php
sudo: required
php:
- 5.3
- 5.4
- 5.5
- 5.6
- hhvm
env:
  global:
    VERSION=45
    DOCKER_VERSION=1.12.0~rc2
before_script:
- composer install
install:
- bin/install-docker
script:
- bin/unit-tests
- bin/integration-tests 45
- bin/check-style --warning-severity=0 src
notifications:
  email: false
  slack:
    secure: uttJ78cpkV9czhoKXtAoop8UBWPVtF+fwKlKS47c4EW7ZfVx9jAII2yLb5yZjdLDnM7YAluujUBIqyESvwLY0h7azLsorSIEqNt9GlBi4B7DSGAdo46lFbqsdjrLwM1gOhiP7Fl4hFiQ2+jA9Fsj3W2yZ6rbF7endv7Gx5FMlFg=
